/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author NQHuy
 * 
 */
public class EmployeesManagement extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    String User;
    /**
     * Creates new form EmployeesManagement
     */
    public EmployeesManagement(String User) {
        super("Employees Management");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ICoinLoGo/employee.png")));
        this.User=User;
        conn=javaconnect.ConnectDB();
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        Toolkit toolkit=getToolkit();
        Dimension size;
        size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        loadData();
        setEnabledButton();
        
        
        
    }
    private void setEnabledButton(){
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);   
    }
    
    private void Failed(String str1){
        ImageIcon icon = new ImageIcon(getClass().getResource("/IconForm/icons8_failed.png"));
        JOptionPane.showMessageDialog(null, str1,"...Warning...",JOptionPane.DEFAULT_OPTION, icon);
    }
    
    private void Completed(String str1){
        ImageIcon icon = new ImageIcon(getClass().getResource("/IconForm/icons8_completed.png"));
        JOptionPane.showMessageDialog(null, str1, "....Notification...",JOptionPane.DEFAULT_OPTION, icon);
    }
    
    private void loadData(){
        String[] arry={"User Name","Name","Phone","Birth","Security Question","Answer","Password","Role"};
            DefaultTableModel model=new DefaultTableModel(arry,0);
            tableE.setModel(model);
        String sql="select * from Account order by Username";
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                while(rs.next()){
                    Vector vector=new Vector();
                    vector.add(rs.getString("Username").trim());
                    vector.add(rs.getString("Name").trim());
                    vector.add(rs.getString("YouPhone").trim());
                    vector.add(rs.getString("Birth").trim());
                    vector.add(rs.getString("SecurityQuestions").trim());
                    vector.add(rs.getString("Answer").trim());
                    vector.add(rs.getString("Password").trim());
                    vector.add(rs.getString("Role").trim());
                    model.addRow(vector);
                }
                pst.close();
                rs.close();
            }
            catch(Exception ex){
                ex.printStackTrace();
            }
    }

    private EmployeesManagement() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableE = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userNameE = new javax.swing.JTextField();
        nameE = new javax.swing.JTextField();
        phoneE = new javax.swing.JTextField();
        securityQuestionsE = new javax.swing.JTextField();
        answerE = new javax.swing.JTextField();
        passwordE = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        birthE = new javax.swing.JTextField();
        roleE = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        btnFindE = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableE.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        tableE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Name", "Phone", "Security Questions", "Answer", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel2.setText("Information");

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel3.setText("User Name:");

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel5.setText("Phone:");

        jLabel6.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel6.setText("Security Questions:");

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel7.setText("Answer:");

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel8.setText("Password:");

        userNameE.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        userNameE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameEMouseClicked(evt);
            }
        });
        userNameE.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                userNameECaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                userNameEInputMethodTextChanged(evt);
            }
        });

        nameE.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        phoneE.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        phoneE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneEActionPerformed(evt);
            }
        });

        securityQuestionsE.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        answerE.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        passwordE.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-add-male-user-50.png"))); // NOI18N
        btnAdd.setToolTipText("Add Employee");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-edit-profile-50.png"))); // NOI18N
        btnEdit.setToolTipText("Edit Employee");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-delete-male-user-50.png"))); // NOI18N
        btnDelete.setToolTipText("Delete Employee");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-cancel-subscription-50.png"))); // NOI18N
        btnCancel.setToolTipText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-name-20.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-name-tag-20.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-phone-20.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-ask-question-20.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-faq-20.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-password-reset-20.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel15.setText("Birth:");

        birthE.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        roleE.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel16.setText("Role:");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-name-tag-20.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-collaborator-male-20.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-home-50.png"))); // NOI18N
        jButton1.setToolTipText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        btnFindE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-find-and-replace-32.png"))); // NOI18N
        btnFindE.setToolTipText("Find Employee");
        btnFindE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindEActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/icons8-save-50.png"))); // NOI18N
        btnSave.setToolTipText("Save - Updated Employee");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel15)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel16)
                            .addComponent(btnFindE, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(userNameE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(securityQuestionsE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(phoneE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(birthE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nameE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(answerE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(passwordE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roleE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(userNameE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(nameE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(birthE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(securityQuestionsE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(answerE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(passwordE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(roleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFindE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd)
                            .addComponent(btnEdit))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(btnCancel)
                            .addComponent(btnSave)))
                    .addComponent(btnDelete))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home ob=new Home(User);
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEMouseClicked
        // TODO add your handling code here:
        int index=tableE.getSelectedRow();
        TableModel model=tableE.getModel();
        String value1=model.getValueAt(index,0).toString();
        String value2=model.getValueAt(index,1).toString();
        String value3=model.getValueAt(index,2).toString();
        String value4=model.getValueAt(index,3).toString();
        String value5=model.getValueAt(index,4).toString();
        String value6=model.getValueAt(index,5).toString();
        String value7=model.getValueAt(index,6).toString();
        String value8=model.getValueAt(index,7).toString();
        
        userNameE.setText(value1);
        nameE.setText(value2);
        phoneE.setText(value3);
        birthE.setText(value4);  
        securityQuestionsE.setText(value5);
        answerE.setText(value6);
        passwordE.setText(value7);
        roleE.setText(value8);
        btnEdit.setEnabled(true);
        btnCancel.setEnabled(true);
        
    }//GEN-LAST:event_tableEMouseClicked

    private void phoneEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneEActionPerformed

    private void loadTextBox(){
        userNameE.setText("");
        nameE.setText("");
        phoneE.setText("");
        birthE.setText("");  
        securityQuestionsE.setText("");
        answerE.setText("");
        passwordE.setText("");
        roleE.setText("");
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        loadTextBox();
        setEnabledButton();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnDelete.setEnabled(true);
        btnAdd.setEnabled(true);
        btnCancel.setEnabled(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void userNameEInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_userNameEInputMethodTextChanged
        // TODO add your handling code here:
        btnAdd.setEnabled(true);
        
    }//GEN-LAST:event_userNameEInputMethodTextChanged

    private void userNameEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameEMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userNameEMouseClicked

    private void userNameECaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_userNameECaretPositionChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userNameECaretPositionChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
            if((userNameE.getText()).equals("")){
                Failed("Please Fill User Name");
            }
            else if ((nameE.getText()).equals("")){
                Failed("Please Fill Name");
            }
            else if ((phoneE.getText()).equals("")){
                Failed("Please Fill Your Phone");
            }
            else if ((birthE.getText()).equals("")){
                Failed("Please Fill Birth");
            }
            else if ((securityQuestionsE.getText()).equals("")){
                Failed("Please Fill Security Question");
            }
            else if ((answerE.getText()).equals("")){
                Failed("Please Answer The Security Questions");
            }
            else if ((passwordE.getText().equals(""))){
               Failed("Please Fill Password");
            }
            else if ((roleE.getText().equals(""))){
                Failed("Please Fill Role");
            }
            else{
                String sql="Insert into Account (Username,Name,YouPhone,Birth,SecurityQuestions,Answer,Password,Role) values (?,?,?,?,?,?,?,?)";
                pst=conn.prepareStatement(sql);
                pst.setString(1,userNameE.getText());
                pst.setString(2,nameE.getText());
                pst.setString(3,phoneE.getText());
                pst.setString(4,birthE.getText());
                pst.setString(5,securityQuestionsE.getText());
                pst.setString(6,answerE.getText());
                pst.setString(7,passwordE.getText());
                pst.setString(8,roleE.getText());
                pst.execute();
                Completed("Add account completed!");
                pst.close();
                loadTextBox();
                loadData();
            }
        }catch(Exception e){
            Failed("Add Account Failed!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try{
            if((userNameE.getText()).equals("")){
                Failed("Please Fill User Name");
            }
            else if ((nameE.getText()).equals("")){
                Failed("Please Fill Name");
            }
            else if ((phoneE.getText()).equals("")){
                Failed("Please Fill Your Phone");
            }
            else if ((birthE.getText()).equals("")){
               Failed("Please Fill Birth");
            }
            else if ((securityQuestionsE.getText()).equals("")){
                Failed("Please Fill Security Question");
            }
            else if ((answerE.getText()).equals("")){
               Failed("Please Answer The Security Questions");
            }
            else if ((passwordE.getText().equals(""))){
                Failed("Please Fill Password");
            }
            else if ((roleE.getText().equals(""))){
                Failed("Please Fill Role");
            }
            else{
                String sql="delete from Account where Username=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1,userNameE.getText());
                pst.execute();
                Completed("Delete Completed!");
                loadTextBox();
                loadData();
                pst.close();
            }
        }catch(Exception e){
            Failed("Delete Failed!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String userName=userNameE.getText();
        String name=nameE.getText();
        String phone=phoneE.getText();
        String birth=birthE.getText();  
        String securityQuestions=securityQuestionsE.getText();
        String answer=answerE.getText();
        String password=passwordE.getText();
        String role=roleE.getText();
        String sql="select * from Account where UserName='"+userName+"'";
        if((userNameE.getText()).equals("")){
                Failed("Please Fill User Name");
            }
            else if ((nameE.getText()).equals("")){
                Failed("Please Fill Name");
            }
            else if ((phoneE.getText()).equals("")){
                Failed("Please Fill Your Phone");
            }
            else if ((birthE.getText()).equals("")){
                Failed("Please Fill Birth");
            }
            else if ((securityQuestionsE.getText()).equals("")){
                Failed("Please Fill Security Question");
            }
            else if ((answerE.getText()).equals("")){
                Failed("Please Answer The Security Questions");
            }
            else if ((passwordE.getText().equals(""))){
                Failed("Please Fill Password");
            }
            else if ((roleE.getText().equals(""))){
                Failed("Please Fill Role");
            }
            else{
                try{
                    pst=conn.prepareStatement(sql);
                    rs=pst.executeQuery();
                    if ((rs.getString(1)).equals(userName)){
                        try {           
                            PreparedStatement st = conn.prepareStatement("UPDATE Account SET Name=?, YouPhone = ?, Birth = ?, SecurityQuestions = ?, Answer = ?, Password = ?, Role = ? WHERE UserName = ?");
                            st.setString(1,name);
                            st.setString(2,phone);
                            st.setString(3,birth);
                            st.setString(4,securityQuestions);
                            st.setString(5,answer);
                            st.setString(6,password);
                            st.setString(7,role);
                            st.setString(8,userName);
                            st.executeUpdate();
                            Completed("Update Completed!");
                            rs.close();
                            pst.close();
                            st.close();
                            loadData();
                        }
                        catch (Exception e ) {
                            Failed( "Update Failed");      
                        }           
                    }
                    else{
                        Failed("Incorrect User Name For Update - Please Try Again!");
                    }

                }catch(Exception e){
                    Failed("Update Failed - Not Contain User Name");
                }
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnFindEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeesManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerE;
    private javax.swing.JTextField birthE;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFindE;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField nameE;
    private javax.swing.JTextField passwordE;
    private javax.swing.JTextField phoneE;
    private javax.swing.JTextField roleE;
    private javax.swing.JTextField securityQuestionsE;
    private javax.swing.JTable tableE;
    private javax.swing.JTextField userNameE;
    // End of variables declaration//GEN-END:variables
}
