/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import java.sql.*;
import static java.util.Arrays.equals;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author NQHuy
 */
public class SignIn extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form SignIn
     */
    public SignIn() {
        super("Sign In");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ICoinLoGo/signin.png")));
        initComponents();
        conn=javaconnect.ConnectDB();
        setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setVisible(true);
        setResizable(false);
        Toolkit toolkit=getToolkit();
        Dimension size;
        size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnAccountant = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Password2 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        SecurityQuestions = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnPersion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnManager = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Password1 = new javax.swing.JPasswordField();
        Name = new javax.swing.JTextField();
        YourPhone = new javax.swing.JTextField();
        Birth = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Answer = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnAccountant.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        btnAccountant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/worker.png"))); // NOI18N
        btnAccountant.setText("Accountant");
        btnAccountant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountantActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Create Account");

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel4.setText("Birth:");

        Password2.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel10.setText("Answer:");

        SecurityQuestions.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        SecurityQuestions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Who is your mother?", "What is your nick name?", "Who is your best friend?" }));
        SecurityQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecurityQuestionsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel7.setText("Password again:");

        btnPersion.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        btnPersion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/employee.png"))); // NOI18N
        btnPersion.setText("Person");
        btnPersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel3.setText("Your Phone:");

        jLabel6.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel6.setText("Password:");

        Username.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel9.setText("You are:");

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel2.setText("Name:");

        btnManager.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        btnManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/manager.png"))); // NOI18N
        btnManager.setText("Manager");
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel1.setText("User name: ");

        Password1.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        Name.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        YourPhone.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        Birth.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        jLabel5.setText("Security Questions:");

        Answer.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N

        btnBack.setFont(new java.awt.Font("Sitka Banner", 0, 15)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IcoinUI/right-arrow.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setMaximumSize(new java.awt.Dimension(103, 29));
        btnBack.setMinimumSize(new java.awt.Dimension(103, 29));
        btnBack.setPreferredSize(new java.awt.Dimension(103, 29));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Answer)
                                        .addComponent(SecurityQuestions, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Birth)
                                        .addComponent(Name)
                                        .addComponent(Username)
                                        .addComponent(YourPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Password2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(btnPersion)
                        .addGap(18, 18, 18)
                        .addComponent(btnManager)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAccountant)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(YourPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(SecurityQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Answer)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPersion)
                        .addComponent(btnManager)
                        .addComponent(btnAccountant)))
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(461, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void SecurityQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecurityQuestionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecurityQuestionsActionPerformed

    private void btnAccountantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountantActionPerformed
        // TODO add your handling code here:
        
            if((Username.getText()).equals("")){
                Failed("Please Fill User Name - Importan!");
            }
            else if ((Name.getText()).equals("")){
                Failed("Please Fill Name - Importan!");
            }
            else if ((YourPhone.getText()).equals("")){
                Failed("Please Fill Your Phone - Importan!");
            }
            else if ((Birth.getText()).equals("")){
                Failed("Please Fill Birth - Importan!");
            }
            else if ((Answer.getText()).equals("")){
                Failed("Please Answer The Security Questions - Importan!");
            }
            else if (!(Password1.getText().equals(Password2.getText()))){
                Failed("Password is incorrect - Check!");
            }
            else{
                try{
                    String sql="Insert into Account (Username,Name,YouPhone,Birth,SecurityQuestions,Answer,Password,Role) values (?,?,?,?,?,?,?,?)";
                    pst=conn.prepareStatement(sql);
                    pst.setString(1,Username.getText());
                    pst.setString(2,Name.getText());
                    pst.setString(3,YourPhone.getText());
                    pst.setString(4,Birth.getText());
                    pst.setString(5,(String)SecurityQuestions.getSelectedItem());
                    pst.setString(6,Answer.getText());
                    pst.setString(7,Password1.getText());
                    pst.setString(8,"Accountant");
                    pst.execute();
                    Completed("New Account Create!");
                    pst.close();
                }catch(Exception e){
                    Failed("User Name Has Existed");
                }
            }
    }//GEN-LAST:event_btnAccountantActionPerformed

    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
        // TODO add your handling code here:
        
            if((Username.getText()).equals("")){
                Failed("Please Fill User Name - Importan!");
            }
            else if ((Name.getText()).equals("")){
                Failed("Please Fill Name - Importan!");
            }
            else if ((YourPhone.getText()).equals("")){
                Failed("Please Fill Your Phone - Importan!");
            }
            else if ((Birth.getText()).equals("")){
                Failed("Please Fill Birth - Importan!");
            }
            else if ((Answer.getText()).equals("")){
                Failed("Please Answer The Security Questions - Importan!");
            }
            else if (!(Password1.getText().equals(Password2.getText()))){
                Failed("Password is incorrect - Check!");
            }
            else{
                try{
                    String sql="Insert into Account (Username,Name,YouPhone,Birth,SecurityQuestions,Answer,Password,Role) values (?,?,?,?,?,?,?,?)";
                    pst=conn.prepareStatement(sql);
                    pst.setString(1,Username.getText());
                    pst.setString(2,Name.getText());
                    pst.setString(3,YourPhone.getText());
                    pst.setString(4,Birth.getText());
                    pst.setString(5,(String)SecurityQuestions.getSelectedItem());
                    pst.setString(6,Answer.getText());
                    pst.setString(7,Password1.getText());
                    pst.setString(8,"Manager");
                    pst.execute();
                    Completed("New Account Create!");
                    pst.close();
                

                }catch(Exception e){
                    Failed("User Name Has Existed");
                }
            }
    }//GEN-LAST:event_btnManagerActionPerformed

    private void btnPersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersionActionPerformed
        // TODO add your handling code here:
        if((Username.getText()).equals("")){
                Failed("Please Fill User Name - Important!");
            }
            else if ((Name.getText()).equals("")){
                Failed("Please Fill Name - Important!");
            }
            else if ((YourPhone.getText()).equals("")){
                Failed("Please Fill Your Phone - Important!");
            }
            else if ((Birth.getText()).equals("")){
                Failed("Please Fill Birth - Important!");
            }
            else if ((Answer.getText()).equals("")){
                Failed("Please Answer The Security Questions - Important!");
            }
            else if (!(Password1.getText().equals(Password2.getText()))){
                Failed("Password is incorrect - Check!");
            }
            else{
                try{
                        String sql="Insert into Account (Username,Name,YouPhone,Birth,SecurityQuestions,Answer,Password,Role) values (?,?,?,?,?,?,?,?)";
                        pst=conn.prepareStatement(sql);
                        pst.setString(1,Username.getText());
                        pst.setString(2,Name.getText());
                        pst.setString(3,YourPhone.getText());
                        pst.setString(4,Birth.getText());
                        pst.setString(5,(String)SecurityQuestions.getSelectedItem());
                        pst.setString(6,Answer.getText());
                        pst.setString(7,Password1.getText());
                        pst.setString(8,"Persion");
                        pst.execute();
                        pst.close();
                        Completed("New Account Create!");
                    }
                catch(Exception e){
                    Failed("User Name Has Existed");
                }
            }
    }//GEN-LAST:event_btnPersionActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    
    private void Failed(String str1){
        ImageIcon icon = new ImageIcon(getClass().getResource("/IconForm/icons8_failed.png"));
        JOptionPane.showMessageDialog(null, str1,"...Warning...",JOptionPane.DEFAULT_OPTION, icon);
    }
    
    private void Completed(String str1){
        ImageIcon icon = new ImageIcon(getClass().getResource("/IconForm/icons8_completed.png"));
        JOptionPane.showMessageDialog(null, str1, "....Notification...",JOptionPane.DEFAULT_OPTION, icon);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer;
    private javax.swing.JTextField Birth;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JPasswordField Password2;
    private javax.swing.JComboBox<String> SecurityQuestions;
    private javax.swing.JTextField Username;
    private javax.swing.JTextField YourPhone;
    private javax.swing.JButton btnAccountant;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManager;
    private javax.swing.JButton btnPersion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private int length(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
